version: '3.3'
services:
  web:
    build: ./server
    ports:
      - '80:3000'
    volumes:
      - /Users/junjiexu/Qsync/hack-reactor/products-api/server:/app/server
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:6.0.8-alpine
    ports:
      - '6379:6379'
