version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: jack
      POSTGRES_USER: postgres
      POSTGRES_DB: atelier
    volumes:
      - /db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  web:
    image: xdynasty/atelier-server
    depends_on:
      - postgres
    ports:
      - '80:3000'
